// Command speclevel writes the API level of the pinned spec, and the server ref
// it came from, as constants: the CLI sends the level with every request, and a
// server above it refuses its writes.
//
// Usage:
//
//	go run ./tools/speclevel <openapi.json> <SPEC_REF> <out.go>
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

func main() {
	if len(os.Args) != 4 { //nolint:mnd
		fmt.Fprintln(os.Stderr, "usage: speclevel <openapi.json> <SPEC_REF> <out.go>")
		os.Exit(2) //nolint:mnd
	}
	if err := run(os.Args[1], os.Args[2], os.Args[3]); err != nil {
		fmt.Fprintln(os.Stderr, "speclevel:", err)
		os.Exit(1)
	}
}

func run(specPath, refPath, outPath string) error {
	data, err := os.ReadFile(specPath) //nolint:gosec // the Makefile's path
	if err != nil {
		return err
	}
	var spec struct {
		Info struct {
			Level int `json:"x-api-level"`
		} `json:"info"`
	}
	if err = json.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("%s: %w", specPath, err)
	}
	if spec.Info.Level < 1 {
		return fmt.Errorf("%s has no x-api-level: it predates hivepaas ea89ac59", specPath)
	}
	ref, err := os.ReadFile(refPath) //nolint:gosec // the Makefile's path
	if err != nil {
		return err
	}
	out := fmt.Sprintf(`// Code generated by tools/speclevel from openapi.json and SPEC_REF. DO NOT EDIT.

package api

// APILevel is the API level of the spec this client was generated from. A server
// whose level is higher refuses the CLI's writes.
const APILevel = %d

// SpecRef is the hivepaas release, or commit, the spec was taken from.
const SpecRef = %q
`, spec.Info.Level, strings.TrimSpace(string(ref)))
	return os.WriteFile(outPath, []byte(out), 0o644) //nolint:gosec,mnd // a source file, from the Makefile's paths
}
