// Package api is the HivePaaS API's client, generated by oapi-codegen from
// openapi.json - the spec of the server release named in SPEC_REF. Nothing here
// is written by hand but this file: `make gen` writes client.gen.go and
// level_gen.go, `make update-spec` takes another spec. See
// docs/superpowers/specs/2026-10-08-cli-design.md, section 10.
package api
