// Code generated by tools/speclevel from openapi.json and SPEC_REF. DO NOT EDIT.

package api

// APILevel is the API level of the spec this client was generated from. A server
// whose level is higher refuses the CLI's writes.
const APILevel = 2

// SpecRef is the hivepaas release, or commit, the spec was taken from.
const SpecRef = "430eb7ca"
